.TH %PROGNAME% 1 "2017-05-22" "%PROGNAME% %VERSION%"

.SH NAME
%PROGNAME% \- Compress or decompress .%SUFFIX% files

.SH SYNOPSIS
.B %PROGNAME%
.RB [ -1234567890cdzfhklLqrtvV ]
.RB [ "-o filename" ]
.RB [ "-S suffix" ]
.RB [ "file ..." ]

.SH DESCRIPTION
.B %PROGNAME%
is a multithreaded compression utility for %ALGORITHM% with a command line
syntax similar to gzip or bzip2.

.SH OPTIONS

.TP
.BI -%LMIN%..%LMAX%
Use the compression method with a level -%LMIN% to -%LMAX%.
.br
Compression level -%LMIN% is the fastest, but provides a poorer level
of compression.
.br
Compression level -%LMAX% provides the best level of compression, but is
also the slowest.
.br
The default is -%LDEF%.

.TP
.BI -c
Compressed or uncompressed output is written to the standard output. No files
are modified (force zcat mode).

.TP
.BI -d
Decompress the source files instead of compressing them.

.TP
.BI -z
The complement to -d: forces compression.

.TP
.BI -f
Force compression of file, even if it is not actually reduced in size.
.br
Additionally, files are overwritten without prompting for confirmation.

.TP
.BI -h
Print a short help message.

.TP
.BI -k
Keep input files after compression or decompression.

.TP
.BI -l
List information for the specified compressed files.

.TP
.BI -L
Display the %PROGNAME% license and quit.

.TP
.BI -q
Be quiet: suppress all messages.

.TP
.BI -r
Recursive mode: compress will descend into specified directories.

.TP
.BI -S \ suffix
Set the suffix for compressed files. Default: .%SUFFIX%

.TP
.BI -o \ filename
Set the output file name.

.TP
.BI -t
Test the integrity of each file leaving any files intact.

.TP
.BI -v
Print the percentage reduction of each file and other information.

.TP
.BI -V
Print the version and exit.

.SH EXIT STATUS
The %PROGNAME% utility exits with one of the following values:
.TP 5
.BI 0
Success.
.TP 5
.BI 1
An error occurred.
.TP 5
.BI 2
At least one of the specified files was not compressed since -f was not
specified and compression would have resulted in a size increase.

.SH EXAMPLES
.TP 0
.B # compress using shell pipe:
cat somefile | %PROGNAME% > somefile.%SUFFIX%
.br
echo "hello *world*" | %PROGNAME% > hello.%SUFFIX%
.TP 0
.B # compress using the -o option:
%PROGNAME% \-o out.%SUFFIX% inputfile
.br
cat source | %PROGNAME% \-o out.%SUFFIX%
.TP 0
.B # compress all files in the current directory with level %LDEF%:
%PROGNAME% \-%LDEF% *
.TP 0
.B # decompress using shell pipe:
cat somefile.%SUFFIX% | %PROGNAME% -d > somefile

.SH HOMEPAGE
More information about %ALGORITHM% can be found here: %HOMEPAGE%

.SH BUGS
Please report any bugs to https://github.com/mcmilk/zstdmt/issues

.SH LICENSE
Copyright \[co] 2016 - 2017, Tino Reichardt, BSD License

.SH "SEE ALSO"
.BR bzip2 (1),
.BR gzip (1),
.BR lz4 (1),
.BR xz (1),
.BR zstd (1)
