#!/bin/bash

######################################################################
# configuration:
# - Intel(R) Core(TM) i7-3632QM, limited to 1,2 .. 1,8 GHz
# - data.tar contains the tarred silesia directory
######################################################################

../zstd-st -H > ./zstd.log
#../zstd-mt -H > ./zstd-mt.log
#../zstd-mt2 -H > ./zstd-mt2.log

for l in 1 5; do
 for i in 1; do
  for t in 1 2 4 6 8 12; do
   #echo -n "ST-L" >> zstd.log
   #../zstd-st -l $l -i $i -t $t data.tar /dev/null >> ./zstd.log

   echo -n "MT-L" >> zstd.log
   ../zstd-mt -l $l -i $i -t $t data.tar /dev/null >> ./zstd.log

   echo -n "MT2-L" >> zstd.log
   ../zstd-mt2 -l $l -i $i -t $t data.tar /dev/null >> ./zstd.log
  done
 done
done
