#!/bin/bash

######################################################################
# configuration:
# - Intel(R) Core(TM) i7-3632QM, limited to 1,2 .. 1,8 GHz
# - data.tar contains the tarred silesia directory
######################################################################

#strace -f -oX 
../zstd-mt  -l5 -t 1 data.tar data.tar.X1 > ./zstd-mt1.log
